# Configuration for Development environment (dev)
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/movie_booking_system"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
JWT_ACCESS_EXPIRATION: 999d
JWT_REFRESH_EXPIRATION: 999d